@startuml

package SliceableObjects {

    interface ISliceableObject{
        +getObjectType(): String
        +getXlocation(): int
        +getYlocation(): int
        +getMaxHeight(): int
        +getInitialVelocity(): int
        +getFallingVelocity(): int
        +isSliced(): Boolean
        +hasMovedOffScreen(): Boolean
        +slice()
        +move()

    }

    Class SliceableObject{
        -xLocation:int
        -yLocation:int
        -maxHeight:int
        -initialVelocity: int
        -fallingVelocity: int
        -isSliced: Boolean
        -hasMovedOffScreen: Boolean
        -ObjectType: String
        -images: ImageView
    }


    ISliceableObject <|-- SliceableObject

    SliceableObject <|-- Fruit
    SliceableObject <|--  Bomb

    Fruit <|-- SlowFruit
    Fruit <|-- NormalFruit
    Fruit <|-- FastFruit
    FastFruit <|-- LifeFruit
    FastFruit <|-- ExtraBonusFruit

    Bomb <|-- DangerousBomb
    Bomb <|-- FatalBomb


}

@enduml